### ISSUE TITLE
Not all tasks appear in homeassistent

### ISSUE THREAD

**Issue by Carunga** [joeShuff/vikunja-homeassistant#5]
Hi,
nice work you have done! Installation was no problem, but only a subset oft my tasks appear in homeassistant. New tasks do not appear at all.
I'm running homeassistsnt 2025.03 and the latest vikunja. Found nothing in the homeassistant logs. Any ideas what could be wrong or where to look?

**Comment by joeShuff** [comment]
Hi, thanks for trying the integration out!

Without logs I can't do much other than suggest some troubleshooting steps

- Double check the access the API token has. I have put mine to just have all access but the minimum access has been updated in the README.
- Update the logger level of the integration so you can see logs from the integration.
  ```
  logger:
    default: warning
    logs:
      custom_components.vikunja: debug
  ```
